//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment21_WCF_Client.Q2CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Q2CalcService.IQ2_Calc")]
    public interface IQ2_Calc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQ2_Calc/Add2Num", ReplyAction="http://tempuri.org/IQ2_Calc/Add2NumResponse")]
        int Add2Num(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQ2_Calc/Add2Num", ReplyAction="http://tempuri.org/IQ2_Calc/Add2NumResponse")]
        System.Threading.Tasks.Task<int> Add2NumAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQ2_Calc/Sub2Num", ReplyAction="http://tempuri.org/IQ2_Calc/Sub2NumResponse")]
        int Sub2Num(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQ2_Calc/Sub2Num", ReplyAction="http://tempuri.org/IQ2_Calc/Sub2NumResponse")]
        System.Threading.Tasks.Task<int> Sub2NumAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQ2_CalcChannel : Assignment21_WCF_Client.Q2CalcService.IQ2_Calc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Q2_CalcClient : System.ServiceModel.ClientBase<Assignment21_WCF_Client.Q2CalcService.IQ2_Calc>, Assignment21_WCF_Client.Q2CalcService.IQ2_Calc {
        
        public Q2_CalcClient() {
        }
        
        public Q2_CalcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Q2_CalcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Q2_CalcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Q2_CalcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add2Num(int a, int b) {
            return base.Channel.Add2Num(a, b);
        }
        
        public System.Threading.Tasks.Task<int> Add2NumAsync(int a, int b) {
            return base.Channel.Add2NumAsync(a, b);
        }
        
        public int Sub2Num(int a, int b) {
            return base.Channel.Sub2Num(a, b);
        }
        
        public System.Threading.Tasks.Task<int> Sub2NumAsync(int a, int b) {
            return base.Channel.Sub2NumAsync(a, b);
        }
    }
}
